#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
    SELECT 'CREATE DATABASE cowork_config OWNER "${POSTGRES_USER}"'
    WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'cowork_config')\gexec
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "cowork_config" <<-EOSQL
    CREATE SCHEMA IF NOT EXISTS config AUTHORIZATION ${POSTGRES_USER};
    ALTER DATABASE cowork_config SET search_path TO config, public;

    GRANT ALL ON SCHEMA config TO ${POSTGRES_USER};
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA config TO ${POSTGRES_USER};
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA config TO ${POSTGRES_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA config
    GRANT ALL ON TABLES TO ${POSTGRES_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA config
    GRANT ALL ON SEQUENCES TO ${POSTGRES_USER};
EOSQL
