#!/bin/bash
# Assignments are consumed by the sourcing deploy.sh and environment helpers.
# shellcheck disable=SC2034
CONTAINER_PORT=8761
HOST_PORT=${HOST_PORT:-8761}
HEALTH_PATH=/actuator/health
require_env VAULT_EXTERNAL_HOST VAULT_TOKEN KAFKA_BOOTSTRAP_SERVERS LIVEKIT_URL LIVEKIT_WS_URL
add_env SPRING_PROFILES_ACTIVE "$APP_CONFIG_PROFILE"
add_env KAFKA_BOOTSTRAP_SERVERS "$KAFKA_BOOTSTRAP_SERVERS"
add_env VAULT_HOST "$VAULT_EXTERNAL_HOST"
add_env VAULT_SCHEME https
add_env VAULT_PORT "${VAULT_PORT:-443}"
add_env VAULT_TOKEN "$VAULT_TOKEN"
add_env VAULT_BACKEND "${VAULT_BACKEND:-secret}"
object_storage_environment
add_env LIVEKIT_URL "$LIVEKIT_URL"
add_env LIVEKIT_WS_URL "$LIVEKIT_WS_URL"
if [ "$APP_CONFIG_PROFILE" = prod ]; then
  require_env PUBLIC_WEB_ORIGIN PUBLIC_API_BASE_URL GITHUB_APP_SERVICE_URL
  add_env PUBLIC_WEB_ORIGIN "$PUBLIC_WEB_ORIGIN"
  add_env PUBLIC_API_BASE_URL "$PUBLIC_API_BASE_URL"
  add_env GITHUB_APP_SERVICE_URL "$GITHUB_APP_SERVICE_URL"
fi
