#!/bin/bash
# Assignments are consumed by the sourcing deploy.sh and environment helpers.
# shellcheck disable=SC2034
CONTAINER_PORT=8761
HOST_PORT=${HOST_PORT:-8761}
HEALTH_PATH=/actuator/health
require_env VAULT_EXTERNAL_HOST VAULT_TOKEN KAFKA_BOOTSTRAP_SERVERS LIVEKIT_URL LIVEKIT_WS_URL
require_env CONFIG_SERVER_ACCOUNTS_JSON
add_env CONFIG_SERVER_ACCOUNTS_JSON "$CONFIG_SERVER_ACCOUNTS_JSON"
add_env SPRING_PROFILES_ACTIVE "$APP_CONFIG_PROFILE"
add_env KAFKA_BOOTSTRAP_SERVERS "$KAFKA_BOOTSTRAP_SERVERS"
add_env VAULT_HOST "$VAULT_EXTERNAL_HOST"
add_env VAULT_SCHEME https
add_env VAULT_PORT "${VAULT_PORT:-443}"
add_env VAULT_TOKEN "$VAULT_TOKEN"
add_env VAULT_BACKEND "${VAULT_BACKEND:-secret}"
object_storage_environment
add_env LIVEKIT_URL "$LIVEKIT_URL"
add_env LIVEKIT_WS_URL "$LIVEKIT_WS_URL"
if [ "$APP_CONFIG_PROFILE" = prod ]; then
  require_env CONFIG_SERVER_URL EUREKA_SERVER_URL CONFIG_TLS_CERTIFICATE CONFIG_TLS_PRIVATE_KEY CONFIG_ALLOWED_CIDRS
  python3 "${PROD_DIR}/validate-config-vault-token.py"
  add_env CONFIG_TLS_CERTIFICATE "$CONFIG_TLS_CERTIFICATE"
  add_env CONFIG_TLS_PRIVATE_KEY "$CONFIG_TLS_PRIVATE_KEY"
  # The certificate must match the canonical DNS name; never bypass certificate validation.
  HEALTH_BASE_URL="${CONFIG_SERVER_URL%/}"
  source "${PROD_DIR}/lib/config-firewall.sh"
  configure_config_firewall
  require_env PUBLIC_WEB_ORIGINS PUBLIC_API_BASE_URL GITHUB_APP_SERVICE_URL
  add_env PUBLIC_WEB_ORIGINS "$PUBLIC_WEB_ORIGINS"
  add_env PUBLIC_API_BASE_URL "$PUBLIC_API_BASE_URL"
  add_env GITHUB_APP_SERVICE_URL "$GITHUB_APP_SERVICE_URL"
fi
