// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "서비스 생존 여부 확인",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "system"
                ],
                "summary": "헬스 체크",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/notifications/tokens": {
            "post": {
                "description": "사용자의 디바이스 FCM 토큰을 등록합니다",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "FCM 토큰 등록",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "사용자 ID (Gateway 주입)",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "토큰 등록 요청",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_domain_token.registerTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "내부 서버 오류",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/notifications/tokens/{token}": {
            "delete": {
                "description": "사용자의 디바이스 FCM 토큰을 삭제합니다",
                "tags": [
                    "tokens"
                ],
                "summary": "FCM 토큰 삭제",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "사용자 ID (Gateway 주입)",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "FCM 토큰",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "토큰 없음",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "내부 서버 오류",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_domain_token.registerTokenRequest": {
            "type": "object",
            "properties": {
                "platform": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8086",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "cowork-notification API",
	Description:      "FCM 디바이스 토큰 관리 및 푸시 알림 서비스",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
