# 모든 서비스에 공통 적용되는 설정
spring:
  reactor:
    context-propagation: auto
  cloud:
    config:
      uri: http://localhost:8761
    bus:
      enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

sdk:
  logging:
    not-logging-urls:
      - "/actuator/**"
      - "/metrics"
      - "/health"
