server_port: 8082

DB_HOST: mysql
DB_PORT: 3306
DB_NAME: cowork_user
DB_JDBC_URL: jdbc:mysql://mysql:3306/cowork_user?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul

eureka_app_name: cowork-user
eureka_server_url: http://cowork-config:8761/eureka/
eureka_instance_host: cowork-user
eureka_instance_port: 8082

kafka_bootstrap_servers: kafka:9092
kafka_group_id: cowork-user

s3_region: us-east-1
s3_internal_endpoint: ${S3_INTERNAL_ENDPOINT}
s3_public_endpoint: ${S3_PUBLIC_ENDPOINT}
s3_access_key: ${S3_ACCESS_KEY}
s3_secret_key: ${S3_SECRET_KEY}
s3_path_style_access_enabled: true

redis_host: redis
redis_port: 6379

team_service_url: http://cowork-team:8085
