server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cowork_team?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  kafka:
    bootstrap-servers: kafka:9092
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      s3:
        endpoint: ${S3_INTERNAL_ENDPOINT}
        path-style-access-enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://cowork-config:8761/eureka/

object-storage:
  public-endpoint: ${S3_PUBLIC_ENDPOINT}
  public-base-url: ${S3_PUBLIC_BASE_URL}
