server:
  port: 8086

db:
  dsn: cowork:1234@tcp(localhost:3306)/cowork_notification?charset=utf8mb4&parseTime=True&loc=Local

kafka:
  brokers: localhost:9094
  topic: notification.trigger
  group-id: cowork-notification

fcm:
  credentials-file: ../docker/secrets/firebase-credentials.json

preference:
  service-url: http://localhost:9001

eureka:
  server-url: http://localhost:8761/eureka
  app-name: cowork-notification
  instance:
    host: localhost
    port: 8086
