spring.cloud.aws:
  region:
    static: us-east-1
  credentials:
    access-key: ${MINIO_ROOT_USER:minioadmin}
    secret-key: ${MINIO_ROOT_PASSWORD:minioadmin}
  s3:
    endpoint: http://localhost:9000
    path-style-access-enabled: true

s3:
  base-url: http://localhost:9000/${S3_BUCKET:cowork-bucket}
