server:
  port: 8088

spring:
  r2dbc:
    url: r2dbc:mysql://mysql:3306/cowork_roadmap?serverZoneId=Asia/Seoul
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  flyway:
    url: jdbc:mysql://mysql:3306/cowork_roadmap?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false

eureka:
  client:
    service-url:
      defaultZone: http://cowork-config:8761/eureka/

KAFKA_TOPIC_TEAM_MEMBER: team.member.event
KAFKA_GROUP_ID_TEAM_MEMBER: cowork-roadmap.team-member
