// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/voice/channels/{channel_id}/join": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "채널에 입장합니다. LiveKit 토큰과 연결 URL을 반환합니다. 기존 세션이 없으면 새로 생성됩니다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "voice"
                ],
                "summary": "음성 채널 입장",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "채널 ID",
                        "name": "channel_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_domain_voice_room.JoinResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_cowork_cowork-voice_internal_apperr.Error"
                        }
                    },
                    "403": {
                        "description": "채널 멤버가 아님",
                        "schema": {
                            "$ref": "#/definitions/github_com_cowork_cowork-voice_internal_apperr.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cowork_cowork-voice_internal_apperr.Error"
                        }
                    }
                }
            }
        },
        "/voice/channels/{channel_id}/leave": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "채널에서 퇴장합니다. 마지막 참여자가 나가면 방이 자동으로 삭제됩니다.",
                "tags": [
                    "voice"
                ],
                "summary": "음성 채널 퇴장",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "채널 ID",
                        "name": "channel_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "퇴장 성공"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_cowork_cowork-voice_internal_apperr.Error"
                        }
                    },
                    "404": {
                        "description": "활성 세션 없음",
                        "schema": {
                            "$ref": "#/definitions/github_com_cowork_cowork-voice_internal_apperr.Error"
                        }
                    }
                }
            }
        },
        "/voice/channels/{channel_id}/participants": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "현재 음성 채널에 참여 중인 사용자 목록을 반환합니다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "voice"
                ],
                "summary": "채널 참여자 목록 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "채널 ID",
                        "name": "channel_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_domain_voice_room.ParticipantsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_cowork_cowork-voice_internal_apperr.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_cowork_cowork-voice_internal_apperr.Error"
                        }
                    }
                }
            }
        },
        "/voice/sessions/{session_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "session_id로 음성 세션 정보를 조회합니다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "voice"
                ],
                "summary": "세션 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "세션 ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_domain_voice_room.SessionResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_cowork_cowork-voice_internal_apperr.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_cowork_cowork-voice_internal_apperr.Error"
                        }
                    }
                }
            }
        },
        "/voice/webhook": {
            "post": {
                "description": "LiveKit 서버가 전송하는 participant_joined / participant_left / room_finished 이벤트를 처리합니다. LiveKit 서버 내부 호출용이며 직접 호출하지 않습니다.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "webhook"
                ],
                "summary": "LiveKit 웹훅 수신",
                "parameters": [
                    {
                        "type": "string",
                        "description": "LiveKit 웹훅 서명",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_cowork_cowork-voice_internal_apperr.Error": {
            "description": "API 에러 응답",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "NOT_FOUND"
                },
                "message": {
                    "type": "string",
                    "example": "session not found"
                },
                "status": {
                    "type": "integer",
                    "example": 404
                }
            }
        },
        "internal_domain_voice_room.JoinResponse": {
            "type": "object",
            "properties": {
                "livekit_url": {
                    "type": "string",
                    "example": "wss://livekit.example.com"
                },
                "room_name": {
                    "type": "string",
                    "example": "channel-42"
                },
                "session_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiJ9..."
                }
            }
        },
        "internal_domain_voice_room.ParticipantResponse": {
            "type": "object",
            "properties": {
                "joined_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_domain_voice_room.ParticipantsResponse": {
            "type": "object",
            "properties": {
                "channel_id": {
                    "type": "integer",
                    "example": 42
                },
                "participants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_domain_voice_room.ParticipantResponse"
                    }
                },
                "room_name": {
                    "type": "string",
                    "example": "channel-42"
                }
            }
        },
        "internal_domain_voice_room.SessionResponse": {
            "type": "object",
            "properties": {
                "channel_id": {
                    "type": "integer",
                    "example": 42
                },
                "ended_at": {
                    "type": "string",
                    "example": "2024-01-01T01:00:00Z"
                },
                "session_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "started_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "status": {
                    "type": "string",
                    "example": "active"
                },
                "team_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "\"Bearer {access_token}\" 형식으로 입력하세요.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Cowork Voice API",
	Description:      "음성 채널 서비스 — LiveKit 기반 음성 통화 세션 관리",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
