#!/bin/sh
set -eu

: "${VAULT_ADDR:?VAULT_ADDR is required}"
: "${VAULT_TOKEN:?VAULT_TOKEN is required}"

JWT_SECRET=${JWT_SECRET:-}
SECRET_KEY_BASE=${SECRET_KEY_BASE:-}
MYSQL_USER=${MYSQL_USER:-}
MYSQL_PASSWORD=${MYSQL_PASSWORD:-}
POSTGRES_USER=${POSTGRES_USER:-}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-}
MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-}
MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-}
DATAGSM_CLIENT_ID=${DATAGSM_CLIENT_ID:-}
ACCOUNT_CREDENTIAL_ENCRYPTION_KEY=${ACCOUNT_CREDENTIAL_ENCRYPTION_KEY:-}
ACCOUNT_SHARE_OAUTH_STATE_SECRET=${ACCOUNT_SHARE_OAUTH_STATE_SECRET:-}
TEAM_GITHUB_STATE_SECRET=${TEAM_GITHUB_STATE_SECRET:-}
GITHUB_APP_SLUG=${GITHUB_APP_SLUG:-}
GITHUB_APP_INTERNAL_API_KEY=${GITHUB_APP_INTERNAL_API_KEY:-}
S3_ACCESS_KEY=${S3_ACCESS_KEY:-seaweedfsadmin}
S3_SECRET_KEY=${S3_SECRET_KEY:-seaweedfsadmin}
LIVEKIT_API_KEY=${LIVEKIT_API_KEY:-devkey}
LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET:-devsecret}

vault secrets enable -version=2 -path=secret kv >/dev/null 2>&1 || true

vault kv put secret/application \
  JWT_SECRET="${JWT_SECRET}" \
  MYSQL_USER="${MYSQL_USER}" \
  MYSQL_PASSWORD="${MYSQL_PASSWORD}" \
  POSTGRES_USER="${POSTGRES_USER}" \
  POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" \
  S3_ACCESS_KEY="${S3_ACCESS_KEY}" \
  S3_SECRET_KEY="${S3_SECRET_KEY}" >/dev/null

vault kv put secret/cowork-gateway \
  jwt.secret="${JWT_SECRET}" >/dev/null

vault kv put secret/cowork-authorization \
  DB_DSN="${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(mysql:3306)/cowork_authorization?charset=utf8mb4&parseTime=True&loc=Local" \
  DATAGSM_CLIENT_ID="${DATAGSM_CLIENT_ID}" \
  DATAGSM_WEBHOOK_SECRET="${DATAGSM_WEBHOOK_SECRET:-}" \
  JWT_SECRET="${JWT_SECRET}" >/dev/null

vault kv put secret/cowork-notification \
  db.dsn="${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(mysql:3306)/cowork_notification?charset=utf8mb4&parseTime=True&loc=Local" >/dev/null

vault kv put secret/cowork-preference \
  preference.db.username="${POSTGRES_USER}" \
  preference.db.password="${POSTGRES_PASSWORD}" >/dev/null

vault kv put secret/cowork-user \
  DB_USERNAME="${MYSQL_USER}" \
  DB_PASSWORD="${MYSQL_PASSWORD}" \
  SECRET_KEY_BASE="${SECRET_KEY_BASE}" >/dev/null

vault kv put secret/cowork-team \
  TEAM_GITHUB_STATE_SECRET="${TEAM_GITHUB_STATE_SECRET}" \
  GITHUB_APP_SLUG="${GITHUB_APP_SLUG}" >/dev/null

vault kv put secret/cowork-project \
  github-app.internal-api-key="${GITHUB_APP_INTERNAL_API_KEY:-}" \
  TEAM_GITHUB_STATE_SECRET="${TEAM_GITHUB_STATE_SECRET}" >/dev/null

vault kv put secret/cowork-voice \
  MONGODB_URI="mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/cowork_voice?authSource=admin" \
  LIVEKIT_API_KEY="${LIVEKIT_API_KEY}" \
  LIVEKIT_API_SECRET="${LIVEKIT_API_SECRET}" >/dev/null

vault kv put secret/cowork-chat \
  MONGODB_URI="mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/cowork_chat?authSource=admin" \
  DISCORD_WEBHOOK_URL="${DISCORD_WEBHOOK_URL:-}" >/dev/null

vault kv put secret/cowork-channel \
  ACCOUNT_CREDENTIAL_ENCRYPTION_KEY="${ACCOUNT_CREDENTIAL_ENCRYPTION_KEY}" \
  ACCOUNT_SHARE_OAUTH_STATE_SECRET="${ACCOUNT_SHARE_OAUTH_STATE_SECRET}" \
  GITHUB_ACCOUNT_SHARE_CLIENT_ID="${GITHUB_ACCOUNT_SHARE_CLIENT_ID:-}" \
  GITHUB_ACCOUNT_SHARE_CLIENT_SECRET="${GITHUB_ACCOUNT_SHARE_CLIENT_SECRET:-}" \
  NOTION_ACCOUNT_SHARE_CLIENT_ID="${NOTION_ACCOUNT_SHARE_CLIENT_ID:-}" \
  NOTION_ACCOUNT_SHARE_CLIENT_SECRET="${NOTION_ACCOUNT_SHARE_CLIENT_SECRET:-}" \
  JIRA_ACCOUNT_SHARE_CLIENT_ID="${JIRA_ACCOUNT_SHARE_CLIENT_ID:-}" \
  JIRA_ACCOUNT_SHARE_CLIENT_SECRET="${JIRA_ACCOUNT_SHARE_CLIENT_SECRET:-}" \
  GOOGLE_ACCOUNT_SHARE_CLIENT_ID="${GOOGLE_ACCOUNT_SHARE_CLIENT_ID:-}" \
  GOOGLE_ACCOUNT_SHARE_CLIENT_SECRET="${GOOGLE_ACCOUNT_SHARE_CLIENT_SECRET:-}" \
  FACEBOOK_ACCOUNT_SHARE_CLIENT_ID="${FACEBOOK_ACCOUNT_SHARE_CLIENT_ID:-}" \
  FACEBOOK_ACCOUNT_SHARE_CLIENT_SECRET="${FACEBOOK_ACCOUNT_SHARE_CLIENT_SECRET:-}" >/dev/null

echo "Vault secrets initialized."
